function manual
% Nonlinear Principal Component Analysis (NLPCA version 5.0) online manual
%        Copyright (C) 2007   William W. Hsieh
%
% Files in this directory:
%
% setdat.m sets up the demo problem, produces a demo dataset data1.mat.
%------------
% nlpca1.m is the main program for calculating the NLPCA mode 1.
%    (Here the dataset xdata is loaded). Saves mode 1 in mode1.mat.
% nlpca2.m is the main program for calculating the NLPCA mode 2. (See
%     the directory Eg2).
%
% param.m contains the parameters for the problem.
%
% nearest.m finds the nearest neighbours in the dataset.
%
% chooseTestSet.m divides the dataset into a training set & a test
%                 (i.e. validation) set.
%
% calcmode.m computes the NLPCA mode (or PCA mode).
%
% costfn.m computes the costfn.
% mapu.m maps x -> u.
% invmapx.m computes the inverse map u -> xi.
% nondimen.m & dimen.m are used for scaling & descaling the data.
%
% extracalc.m can be used for projecting new data onto an
%   NLPCA mode. Also used in plotting with plmode1.m, pltmode1.m, etc.
%
% out1 is the printout from running nlpca1.
%  [i.e. out1 generated by the Linux command: matlab < nlpca1.m > out1 & ]
% plmode1.m or pltmode1.m plots the output mode 1.
%
%-------------------
%
% In the directory Eg2: 
% A different sample problem is set up containing 2 modes.
% After removing the mode 1 solution from the data, nlpca2.m extracts
% the mode 2 solution and writes mode2.mat.
% Use plmode2.m or pltmode2.m to plot the retrieved mode 2.
%
% In the directory Nb2:
% Instead of retrieving mode 1 and 2 sequentially as in Eg2, a 2-dimensional
% mode is retrieved by having 2 neurons in the bottleneck.
% The main program nlpca.m produces modes.mat and out (the printout file).
% Use plmodes.m to plot the modes.
%
%======================================================================%
% The parameters are stored in param.m.:
% Parameters are classified into 3 categories, `*' means user normally has
% to change the value to fit the problem. `+' means user may want to
% change the value, and `-' means user rarely has to change the value.
%
%+ iprint = 0, 1, 2, 3 increases the amount of printout wanted.
%        (Printout summary can be extracted by the unix grep command:
%         grep # printout_filename)
%
%+ Err_norm = 1 or 2 (L1 or L2 norm to measure error, i.e. using mean
%             absolute error (MAE) or mean square error (MSE) for Err. 
%             L1 is less sensitive but more robust to outliers in the data.
%             
%- linear = 0 means NLPCA; linear = 1 essentially reduces to PCA.
%
%+ nensemble is the no. of runs in the ensemble. (Many runs may
%            converge to shallow local minina and hence wasted).
%
%- testfrac = 0 does not reserve a portion of the data for testing or
%          validation, i.e. all data used for training.  Use only when 
%          data is not noisy, or a linear solution is wanted.       
%  testfrac > 0, say between 0.1 to 0.2, then a fraction of the data
%	   record will be randomly selected as test data.
%
%+ segmentlength = 1 if autocorrelation of the data (in time) is not of
%        concern; otherwise set to about the autocorrelation time scale.     
%
%- overfit_tol is the tolerance for overfitting, should be 0 (recommended)
%      or a small positive number (<< 0.1).
%      Only runs having Err over the test set no worse than
%      (Err over the training set)*(1+overfit_tol) are accepted, 
%      and the selected solution is the run with the lowest Err
%      over all the data.
%      When overfit_tol = 0, program automatically chooses an overfit
%      tolerence level to decide which runs to accept.
%
%- info_crit = 1 uses the information criterion H for model selection,
%            = 0 uses minimum Err for model selection (can overfit).
%
%+ xscaling  controls scaling of the x variables before performing NLPCA. 
%      = -1, no scaling (not recommended unless variables are of order 1).
%      = 0, scales all x variables by removing the mean & dividing by the
%      standard deviation of each variable. 
%      = 1, scales all x variables by removing the mean & dividing by the
%      standard deviation of the 1st x variable. (Etc. for 2, 3, ...)
%      When the x variables are the principal components and the 1st
%      variable is from the leading mode, xscaling = 1 is preferred.
%
%+ penalty_store stores the penalty values. For a run,
%      `penalty' is chosen randomly among the values specified in
%      penalty_store. `penalty' scales the weight
%      penalty term in the cost function. If 0, no penalty used.  
%      Increasing the penalty leads to less nonlinearity (i.e. less 
%      wiggles & zigzags when fitting to the data).     
%
%- maxiter scales the maximum number of function iterations allowed 
%      during optimization. Start with 1, increase if needed.
%
%+ initRand =  a positive integer, initializes the random number
%             generator, used for random initial weights.
%
%- initwt_radius controls the initial random wt. radius for the runs.
%      Adjust this parameter if having convergence problem.
%      (Suggest starting with initwt_radius = 1). The wt. radius is
%      smallest for the first run in the ensemble, increasing by a factor
%      of 4 when the final run is reached (so the earliest runs tend
%      to be more linear than the later runs in the ensemble).
%
% Input dimensions of the networks:
%* l is the no. of x variables
%* m is the no. of hidden neurons after the l x-variables. In nlpca1.m, 
%    m is assigned values specified by m_store.
%+ nbottle is the number of bottleneck neurons.
%
%-------------------------
% Global variables are:
%
% global  iprint Err_norm linear nensemble testfrac segmentlength ...
%  overfit_tol info_crit xscaling penalty penalty_store maxiter initRand ...
%  initwt_radius options  n l m nbottle iter Jscale xmean xstd ntrain ...
%  xtrain utrain xitrain ntest xtest utest xitest Err inearest I H
%
%                   !!!!!!!!!!!!!!!!!!!!!!!!!!!
% Be careful not to introduce a local variable with the same name as one
% of these global variables.
% If you add or remove variables from this global list, it is CRITICAL
% that the same changes are made on ALL of the following files:
% nlpca1.m, nlpca2.m, param.m, calcmode.m, costfn.m, mapu.m, invmapx.m,
% extracalc.m, plmode1.m, pltmode1.m, plmode2.m, pltmode2.m.
%                   !!!!!!!!!!!!!!!!!!!!!!!!!!!
%
% n is the number of observations [automatically determined from xdata].
% xdata is an l*n data matrix, as there are l `x' variables, and n observations.
%
% iter is the number of function iterations.
% Jscale is a scale factor for the cost function J.
% xmean & xstd are the means & standard deviations of the xdata variables.
%
% ntrain, ntest are the number of observations for training and for testing.
% xtrain, xtest are the x data used for training and testing.
% utrain, utest are the bottleneck neuron values (the NLPC) during
%               training and testing. mean(utrain) = 0, &
%               utrain*utrain'/ntrain = 1 is forced on the cost fn. J.
% xitrain, xitest are the model predicted values for x during training
%                 and testing. 
% Err is the error of x over all data (training+testing), Err can be the
%      MAE or the MSE (as specified by Err_norm).
% 
% inearest indicates the location of the nearest neighbour for each datum.
% I is the inconsistency index, measuring the inconsistency between the
%   NLPC of nearest neighbours.
% H is the holistic information criterion for selecting the best model
%   among models with various 'm' and 'penalty'. 
%   When nbottle is 1:
%   H = MSE*I if Err_norm = 2;   H = (MAE^2)*I if Err_norm = 1.
%
%========================================================================
